version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quote-vote-postgres
    restart: always
    environment:
      POSTGRES_USER: quoteuser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: quote_vote
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote-vote-backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: quoteuser
      DB_PASSWORD: password123
      DB_NAME: quote_vote
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
