# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quote-vote-postgres
    restart: always
    environment:
      POSTGRES_USER: quoteuser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: quote_vote
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
